### PR TITLE
Write chefspec matchers.

### PR DESCRIPTION
**Pull request by erinn**
Custom matchers are needed for chefspec tests to work.

### CODE REVIEW

**Comment by adamleff** [comment]
Thanks for your contribution!

**Comment by erinn** [comment]
Can I kindly ask for a quick release on this so I can drop my fork and
use the supermarket release?

-Erinn

**Comment by adamleff** [comment]
I'm actually doing it right now :)

**Comment by adamleff** [comment]
v0.5.0 released to the supermarket.

**Pull request merged**
