### PR TITLE
Install yum-plugin-security to ensure --sec-severity works on rhel6

### PR DESCRIPTION
**Pull request by civik**
When installing errata on RHEL6, the yum option '--sec-severity' will not work unless the 'yum-plugin-security'  package is installed.  This appears to be just a part of yum in RHEL7.  This will add the package if needed when installing errata.

### CODE REVIEW

**Comment by civik** [comment]
I read the previous issue - The behavior you describe where installing the security plugin simply upgrades yum -  I can reproduce in yum 3.4.3 on rhel7.1 but not in yum 3.2.29 on rhel 6.7.  On 6.7 there is an actual noarch package 'yum-plugin-security' in the 'rhel-6-server-rpms' repo.  Looks to me like this might be needed in rhel6.  Thus the PR ;)

**Comment by adamleff** [comment]
@civik you are correct! I swore I tested this on RHEL6, but I think I may have started a RHEL7 instance by accident.

I appreciate you putting this PR together. Could you help with two things before I merge-and-release?
- Change your yum_package to use an `only_if` condition rather than wrapping it in an `if` block - this will address the Foodcritic FC023 warning and be more "chef like" :)
- Add some ChefSpec tests to prevent future regressions. I can help with this if you're not familiar, but basically, we should ensure the existing chefspec runner assumes RHEL7 and ensures the package isn't attempted to be installed, and then add another chefspec runner for RHEL6 that ensures the package is installed.

Thanks again for the contribution - let me know how I can help.

**Comment by adamleff** [comment]
Also, thanks for already addressing the rubocop errors :+1:

**Comment by civik** [comment]
Working on it now.  The rspec force is not strong with me but I can usually copypasta something in that works using existing as an example.

**Comment by adamleff** [comment]
@civik give it your best shot, and I'll help you get it over the finish line.

**Comment by civik** [comment]
Looks good I think, looking forward to your feedback!

**Comment by adamleff** [comment]
This looks great!

A few things:
- Let's back out the version bump. I'll take care of that during the release process.
- Can we add the RHEL7 test back in, but just not add a new chef runner?

```
context 'when the host is not rhel6' do
  it 'does not install the yum-security-plugin' do
    # test here
  end
end

context 'when the host is rhel6' do
  let(:chef_run) ...
  # your existing i-expect-chef-to-yum-install test here
end
```

We can go back and add a RHEL7-specific Chefspec runner once a new version of Fauxhai is released that contains the RHEL7 mocked data in the gem (vs. Fauxhai fetching it via HTTP and running into permissions problem like you experienced in Travis).

Let me know if you have any questions - but we're definitely close to merging this!

**Comment by adamleff** [comment]
Also, when you've made the above changes, can you squash into a single commit?  Let me know if you're unclear how to do that.

**Comment by civik** [comment]
Can you handle the squash?

**Comment by adamleff** [comment]
Yup. I'll take care of it. Probably tomorrow.

**Comment by adamleff** [comment]
Rebased / cleaned-up in 417aef83b and merged to master. I'll release a new version on the supermarket shortly.  Thanks!

**Comment by adamleff** [comment]
v0.3.0 has been released to the supermarket this morning.

**Pull request closed without merging**
